### ISSUE TITLE
Bin entries added initially but don't show on full calendar. 

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [nonPointer/Glasgow-Bin-Collection-iCal-Py#1]
Environment:

OS: Ubuntu 22.04
Method: pip3

Hello again and apologies for the very late reply.

The dates/bins generate fine and they show on the initial page after adding the ics file but within the calendar itself it'll only show one bin and the colour is the same for each bin. 

I'm playing around with settings in case it's something I have set wrong. 

This is the initial view. 
![Screenshot_20231111_085747_Calendar](https://github.com/nonPointer/Glasgow-Bin-Collection-iCal-Py/assets/11256455/90170b37-2896-484f-a02a-5eb57b46fb6b)

This is the actual calendar view. November 20th should actually show blue and green bins. 

![Screenshot_20231111_091245_Calendar](https://github.com/nonPointer/Glasgow-Bin-Collection-iCal-Py/assets/11256455/a50c7679-d598-4522-b6ad-1c163763b2b2)

Thanks again for your hard work.

**Comment by nonPointer** [comment]
> it'll only show one bin

Could you explain this further?

> the colour is the same for each bin

Typically, the colour is defined by the Calendar Apps, which allows you to assign a colour for a recurrent event series, or events folder. Since [RFC7986](https://www.rfc-editor.org/rfc/rfc7986.html), it introduced a `COLOR` field to specify the colour of iCal events. But I just tried, the macOS calendar and Outlook don't follow this field.

**Comment by ChiefMedicalOfficer** [comment]
Sorry, poor explanation. So on November 20th there are 2 bins, green and blue but as you can see in the second image only the green bin is shown in the calendar. 

Thanks for the colour explanation.

**Comment by nonPointer** [comment]
It might be the issue of UID collision. I just fix it with UUID4. Could you please try it again with the latest code? Thanks

**Comment by ChiefMedicalOfficer** [comment]
Working great. Nice fix. Thanks again.
